spring.application.name=taskmanager
api.prefix = /${spring.application.name}


# =========================
# Server Configuration
# =========================
server.port=8282

# DataSource Configuration
# =========================
# Spring JPA / Hibernate
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/task_manager
spring.datasource.username=root
spring.datasource.password=Chaitanya@26
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = false
spring.jpa.generate-ddl = true
spring.jpa.properties.hibernate.format_sql = false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging Config
logging.level.org.hibernate.SQL=OFF


# =========================
# File Upload Limits (Optional for Attachments)
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================
# Swagger UI (SpringDoc)
# =========================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Optional: Swagger URL config (default is fine, but for reference)
# springdoc.api-docs.path=/v3/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html

# =========================
# Logging (Optional)
# =========================
logging.level.org.springframework=INFO

# ========================
# JWT Details
# ========================
jwt.secret=yM7p9K8fD3vGtYqX5zJwLmN2RbTcVhW0aYsBPoQxUdEI6OgC4FnZAH1MJkV78X

